name: Ceedling Unit Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.2

            - name: Install dependencies
              run: |
                gem install bundler
                bundle install || gem install ceedling
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Install gcovr
              run: pip install gcovr
            
            - name: Run unit tests with coverage
              run: |
                ceedling gcov:all

            - name: Upload HTML coverage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: build/artifacts/gcov/
